CREATE TABLE SUCURSAL (
	Nombre VARCHAR(30) NOT NULL,
	Distrito VARCHAR(30) NOT NULL,
	Canton VARCHAR(30) NOT NULL,
	Provincia VARCHAR(30) NOT NULL,
	Fecha_apertura DATE NOT NULL,
	Horario_atencion VARCHAR(100) NOT NULL,
	Administrador VARCHAR(9) NOT NULL,
	Capacidad_maxima INT NOT NULL,
	Activacion_spa VARCHAR(15) NOT NULL,
	Activacion_tienda VARCHAR(15) NOT NULL,

	PRIMARY KEY(Nombre)
);

CREATE TABLE PRODUCTOSUCURSAL(
	Sucursal VARCHAR(30) NOT NULL,
	Producto VARCHAR(10) NOT NULL,
	Stock INT NOT NULL,

	PRIMARY KEY (Sucursal, Producto)
);

CREATE TABLE SUCURSALTELEFONOS (
	Sucursal VARCHAR(30) NOT NULL,
	Telefono INT NOT NULL,

	PRIMARY KEY(Sucursal, Telefono)
);

CREATE TABLE EMPLEADO (
	Cedula VARCHAR(9) NOT NULL,
	Primer_nombre VARCHAR(20) NOT NULL,
	Segundo_nombre VARCHAR(20),
	Primer_apellido VARCHAR(20) NOT NULL,
	Segundo_apellido VARCHAR(20),
	Distrito VARCHAR(30) NOT NULL,
	Canton VARCHAR(30) NOT NULL,
	Provincia VARCHAR(30) NOT NULL,
	Salario INT NOT NULL,
	Sucursal VARCHAR(30),
	Correo_electronico VARCHAR(50) NOT NULL,
	Contrasenna VARCHAR(50) NOT NULL,
	Clases_Impartidas INT NOT NULL,
	Puesto INT NOT NULL,
	Planilla INT NOT NULL,

	PRIMARY KEY(Cedula)
);

CREATE TABLE PUESTO (
	Identificador INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(30) NOT NULL,

	PRIMARY KEY(Identificador)
);

CREATE TABLE PLANILLA (
	Identificador INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(15) NOT NULL,

	PRIMARY KEY(Identificador)
);

CREATE TABLE MAQUINA (
	Tipo VARCHAR(20) NOT NULL,
	Marca VARCHAR(20) NOT NULL,
	Numero_serie VARCHAR(10) NOT NULL,
	Costo INT NOT NULL,
	Sucursal VARCHAR(30),

	PRIMARY KEY(Numero_serie)
);

CREATE TABLE CLASE (
	Identificador INT IDENTITY(1,1) NOT NULL,
	Capacidad INT NOT NULL,
	Grupal INT NOT NULL,
	Tipo INT NOT NULL,
	Dia INT NOT NULL,
	Instructor VARCHAR(100) NOT NULL,
	Hora_inicio VARCHAR(5) NOT NULL,
	Hora_fin VARCHAR(5) NOT NULL,


	PRIMARY KEY(Identificador)
);

CREATE TABLE PRODUCTO( -- Productos de tienda
	Codigo_barras VARCHAR(10) NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,
	Costo INT,

	PRIMARY KEY(Codigo_barras)
);


CREATE TABLE TRATAMIENTOSUCURSAL(
	Sucursal VARCHAR(30) NOT NULL,
	Tratamiento INT NOT NULL,

	PRIMARY KEY(Sucursal, Tratamiento)
);

CREATE TABLE TRATAMIENTO ( -- Tratamientos de spa
	Identificador INT IDENTITY(1,1) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,

	PRIMARY KEY(Identificador)
);

CREATE TABLE CLIENTE(
	Cedula VARCHAR(10) NOT NULL,
	Primer_nombre VARCHAR(20) NOT NULL,
	Segundo_nombre VARCHAR(20),
	Primer_apellido VARCHAR(20) NOT NULL,
	Segundo_apellido VARCHAR(20),
	Correo_electronico VARCHAR(50) NOT NULL,
	Distrito VARCHAR(30) NOT NULL,
	Canton VARCHAR(30) NOT NULL,
	Provincia VARCHAR(30) NOT NULL,
	Contrasena VARCHAR(30) NOT NULL,
	Fecha_nacimiento DATE NOT NULL,
	Peso VARCHAR(4) NOT NULL,
	Imc VARCHAR(4) NOT NULL,
	
	PRIMARY KEY(Cedula)
);

CREATE TABLE CLASE_CLIENTE (
	Clase INT NOT NULL,
	Cliente VARCHAR(10) NOT NULL,
	Sucursal VARCHAR(30) NOT NULL,

	PRIMARY KEY(Clase, Cliente,Sucursal)
);

CREATE TABLE TIPO_EQUIPO (
	Identificador VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,

	PRIMARY KEY(Identificador, Descripcion)
);

CREATE TABLE SERVICIO(
	Identificador INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,

	PRIMARY KEY(Identificador)
);
CREATE TABLE CLASESUCURSAL(
	Clase INT NOT NULL,
	Sucursal VARCHAR(30) NOT NULL,

	PRIMARY KEY(Clase, Sucursal)
);


-- Foreign keys
ALTER TABLE SUCURSAL
    ADD FOREIGN KEY (Administrador) REFERENCES EMPLEADO(Cedula);

ALTER TABLE SUCURSALTELEFONOS
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);



ALTER TABLE CLASE_CLIENTE
	ADD FOREIGN KEY (Clase) REFERENCES CLASE(Identificador);
ALTER TABLE CLASE_CLIENTE
	ADD FOREIGN KEY (Cliente) REFERENCES CLIENTE(Cedula);
ALTER TABLE CLASE_CLIENTE
    ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);
	
ALTER TABLE MAQUINA
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);


ALTER TABLE TIPO_EQUIPO
	ADD FOREIGN KEY (Identificador) REFERENCES SUCURSAL(Nombre);


ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (Puesto) REFERENCES PUESTO(Identificador);
ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);
ALTER TABLE EMPLEADO
	ADD FOREIGN KEY (Planilla) REFERENCES PLANILLA(Identificador);
ALTER TABLE PRODUCTOSUCURSAL
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);

ALTER TABLE PRODUCTOSUCURSAL
	ADD FOREIGN KEY (Producto) REFERENCES PRODUCTO(Codigo_barras);

ALTER TABLE TRATAMIENTOSUCURSAL
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);

ALTER TABLE TRATAMIENTOSUCURSAL
	ADD FOREIGN KEY (Tratamiento) REFERENCES TRATAMIENTO(Identificador);

ALTER TABLE CLASESUCURSAL
	ADD FOREIGN KEY (Clase) REFERENCES CLASE(Identificador);
ALTER TABLE CLASESUCURSAL
	ADD FOREIGN KEY (Sucursal) REFERENCES SUCURSAL(Nombre);
ALTER TABLE CLASE
	ADD FOREIGN KEY(Tipo) REFERENCES SERVICIO(Identificador);

ALTER TABLE CLASE
	ADD CONSTRAINT Week_days
	CHECK(1<=Dia AND  Dia<= 7);
